spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  kafka:
    bootstrap-servers: 192.168.99.100:9092
    topic:
      userRegistered: USER_REGISTERED_TOPIC
security:
  basic:
    enabled: false
mail:
   smtp:
      host: smtp.gmail.com
      port: 587
      username: bog.vieru.1977@gmail.com
      password: iancului
      properties.mail.smtp:
        auth: true
        starttls.enable: true